name: DevSync CI Test
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello DevSync, CI is working!"

      - name: Simulate work
        run: sleep 3

      - name: Run Tests
        run: echo "All tests passed successfully!"

      - name: Simulate a failing assertion
        run: |
          echo "Checking expected output..."
          echo "expected: 200, got: 500"
          exit 1
